apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test
  namespace: default
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: deploy-test
  template:
    metadata:
      labels:
        app: deploy-test
    spec:
      containers:
        - name: deploy-test
          image: nginx:1.25.1
          ports:
            - containerPort: 5000
